### ISSUE TITLE
plumber

### ISSUE THREAD

**Issue by harrismcgehee** [terrytangyuan/ctv-model-deployment#1]
Any thoughts about [plumber](https://cran.r-project.org/web/packages/plumber/index.html)?

I'm not an expert in deployment, but I've heard about it as a potential strategy.

**Comment by terrytangyuan** [comment]
Thanks for the issue! Though it’s actually already included if you do a search on the page.

**Comment by harrismcgehee** [comment]
I'm so embarrassed. 🤐 I looked twice!

**Comment by terrytangyuan** [comment]
No problem. It happens. If you have other ideas in the future, please don’t hesitate to let me know as well!
